#lang forge

-- univ and iden refer to the meta-universe (i.e. what atoms are
-- generated by the bounds), and so are incorrect when 
-- considered instances don't fully populate sigs.
--   - forge-alloy/sigs/basicSigs.rkt
option verbosity 10

sig A {}
sig B {}
sig C {}

-- These run statements only produce instances where every
-- sig is fully populated (i.e. 4 of each unless bounds are
-- explicitly set otehrwise).
run {univ = A + B + C + Int}
run {iden = {a1: A, a2: A | a1 = a2} + 
            {b1: B, b2: B | b1 = b2} +
            {c1: C, c2: C | c1 = c2} +
            {i1: Int, i2: Int | i1 = i2}}
